### ISSUE TITLE
[STORY] View products

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#11]
**Related epic**
#1 

**Story**

As a customer,
I can view the site's products
So that I can select one to purchase

**Tasks**
- [x] Design initial product models
- [x] Create templates to display products
- [x] Create initial product listings

**Acceptance criteria**
- [x] Product is visible at expected URL
- [x] Product data is displayed correctly from model
