### ISSUE TITLE
[STORY] Product detail

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#12]
**Related epic**
#1

**Story**

As a customer,
I can view a detailed description of a product,
So that I can make an informed purchase decision

**Tasks**
- [x] Design model with relevant item information fields
- [x] Design template and URLs to display a product in detail

**Acceptance criteria**
- [x] Product detail is accessible at expected URL
- [x] Template variables are displaying model data correctly
- [x] Input is present to add to basket
