### ISSUE TITLE
[STORY] Product categories

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#13]
**Related epic**
#1

**Story**

As a customer,
I can look for products in relevant categories,
So that I can narrow down my product search

**Tasks**
- [x] Make models and fields that gives the product to be sold clearly defined categories
- [x] Make URLs and templates that reflect the way the customer wants to narrow down their search
- [x] Make context processors available for each category
- [x] Ensure entries are sorted alphabetically

**Acceptance criteria**
- [x] Category filter link exists
- [x] Platform filter link exists
- [x] Region filter link exists
- [x] All links return results from selected category only
- [x] All dropdown list entries are sorted alphabetically
