### ISSUE TITLE
[STORY] Product searching

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#14]
**Related epic**
#1 

**Story**

As a customer,
I can use a search bar,
So that I can find items I am looking for directly

**Tasks**
- [x] Include a prominently featured search bar that accepts user input
- [x] Ensure that proper search parameters are accepted and found in the search
- [x] Enable search bar on all appropriate templates

**Acceptance criteria**
- [x] Products are displayed that match the user's search criteria
- [x] All products can be searched for on every page the search bar is on
- [x] Search form cannot be sent without a value
