### ISSUE TITLE
[STORY] Product sorting

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#15]
**Related epic**
#1 

**Story**

As a customer,
I can sort products in various ways,
So that I can narrow down a selection of potential purchases

**Tasks**
- [ ] Add a dropdown menu to sort displayed list products

**Acceptance criteria**
- [ ] Can sort by name
- [ ] Can sort by price
- [ ] Can sort by platform
- [ ] Can sort by year
