### ISSUE TITLE
[STORY] Add/remove items to basket

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#16]
**Related epic**
#2 

**Story**

As a customer,
I can add and remove items to my shopping basket,
So that I can easily buy multiple items at once

**Tasks**
- [x] Create basket app
- [x] Create views, URL and context processors as appropriate
- [x] Integrate a shopping basket feature that tracks the customer's items they want to buy
- [x] Add link to easily access the basket at any time
- [x] Create function to display the basket subtotal

**Acceptance criteria**
- [x] Item can be added to basket
- [x] Item can be removed from the basket
- [x] Basket item quantity is clearly shown
- [x] Basket subtotal is clearly shown
