### ISSUE TITLE
[STORY] Payment for items

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#17]
**Related epic**
#2 

**Story**

As a customer,
I can securely pay for my items with a card,
So that I can safely purchase the items I want to buy

**Tasks**
- [x] Integrate Stripe card payment system
- [x] Integrate Stripe webhooks to confirm payment securely
- [x] Test webhooks in CLI
- [x] Add appropriate Stripe elements with error handling
- [x] Show loading status when payment is sent to Stripe
- [x] Configure redirect and messaging

**Acceptance criteria**
- [x] Stripe API implementation works as intended when used with appropriate card details
- [x] Webhooks listen and handle API calls as intended
- [x] Stripe address element present
- [x] Stripe payment element present
- [x] Full error handling in effect
- [x] Form only submitted when valid
- [x] Submit button and loading status always reflect current state
- [x] Redirect performed on successful payment
- [x] Message shown to indicate successful payment
