### ISSUE TITLE
[STORY] Order summary

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#18]
**Related epic**
#2 

**Story**

As a customer,
I can view an order summary before purchase,
So that I can double-check the grand total and item list before confirming payment

**Tasks**
- [x] Set up template for customer to check out that displays the grand total and information on each item
- [x] Implement AJAX subtotal and delivery charge handling

**Acceptance criteria**
- [x] The customer's grand total is displayed
- [x] The grand total reflects delivery charges correctly
- [x] Delivery charge updates dynamically
- [x] Grand total charge updates dynamically
- [x] No charges are shown when basket is fully emptied
