### ISSUE TITLE
[STORY] Account registration

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#20]
**Related epic**
#3

**Story**

As a customer,
I can register for an account,
So that I can easily manage my data related to past and future purchases

**Tasks**
- [x] Integrate system that enables users to register an account with the site
- [x] Install and configure allauth package

**Acceptance criteria**
- [x] Links to registration templates are easily accessible to the user
- [x] User account is successfully entered into the database
- [x] Account verification in effect
- [x] Users must confirm email address and password on registration form
