### ISSUE TITLE
[STORY] Log in and out

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#21]
**Related epic**
#3 

**Story**

As a customer,
I can log in and out of the site,
So that I can access my data and safely log out once I have finished to protect my data

**Tasks**
- [x] Provide links to log in for non-logged in users
- [x] Provide links to log out for logged in users
- [x] Show feedback message for logging in and out

**Acceptance criteria**
- [x] Log in link is present when not logged in
- [x] Log out link is present when logged in
- [x] Message is displayed following login action
- [x] Message is displayed following logout action
