### ISSUE TITLE
[STORY] Password recovery

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#22]
**Related epic**
#3

**Story**

As a customer,
I can recover my lost password,
So that I can access my data if my original password is lost

**Tasks**
- [x] Enable password recovery features
- [x] Test password recovery features

**Acceptance criteria**
- [x] Email is sent to the specified email address
- [x] A link is provided to perform the password reset
- [x] Access is granted when the user successfully perform the password recovery feature
