### ISSUE TITLE
[STORY] Account verification

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#23]
**Related epic**
#3

**Story**

As an admin,
I can require account verification,
So that I can combat spam accounts from registering

**Tasks**
- [x] Ensure verification is in effect as part of the account registration process
- [x] Test account verification

**Acceptance criteria**
- [x] Verification must be successfully followed before an account is able to login to the site
- [x] Email verification link is sent to the specified email address
- [x] User can login once the verification process has been completed successfully
- [x] User's email address is marked as verified in admin panel upon successful verification
