### ISSUE TITLE
[STORY] Save delivery information

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#25]
**Related epic**
#3

**Story**

As a customer,
I can save data relevant to order checkout,
So that I can save time on future purchases

**Tasks**
- [ ] Give users the option to save the data they enter for delivery
- [ ] Add data to the user's profile
- [ ] Autofill subsequent forms with delivery data

**Acceptance criteria**
- [ ] Users can opt-in to save their delivery data at checkout
- [ ] Delivery data is stored in the user's profile
- [ ] Saved delivery data is used to autofill forms for the customer's subsequent orders

**Comment by jts272** [comment]
This implementation has been refactored. Users will have the ability to manage addresses from their profile for future usage.
