### ISSUE TITLE
[STORY] User profile

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#26]
**Related epic**
#3

**Story**

As a customer,
I can access a profile page,
So that I can view, update and delete my saved data from a central point

**Tasks**
- [x] Add profile page
- [x] Display order history in profile
- [x] Add form to perform CRUD functions on saved data on profile page

**Acceptance criteria**
- [x] Profile page is only accessible for users with registered accounts
- [x] Full order history is accessible from the profile page
- [x] CRUD functionality in effect for customer's data
