### ISSUE TITLE
[STORY] FAQ page

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#27]
**Related epic**
#4

**Story**

As a customer,
I can view a FAQs page,
So that I can easily find answers to the most common business-related queries

**Tasks**
- [x] Create and register new support app
- [x] Register URLs
- [x] Administer role-based access
- [x] Create template for FAQ page
- [x] Display common questions and answers relating to the business
- [x] Give admin CRUD functionality to update questions and answers

**Acceptance criteria**
- [x] FAQ page is present
- [x] Link is clearly provided to FAQ page
- [x] Admin can create a new FAQ
- [x] Admin can update and existing FAQ
- [x] Admin can delete an existing FAQ
- [x] Only admin has access to CRUD functionality
- [x] Messaging system gives feedback on all CRUD actions
