### ISSUE TITLE
[STORY] Relevant external links

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#29]
**Related epic**
#4

**Story**

As a customer,
I can click links to relevant external sites,
So that I can learn more about the business, its services and technologies

**Tasks**
- [x] Add links to related sites
- [x] Ensure appropriate HTML attributes are assigned

**Acceptance criteria**
- [x] Link for Facebook present
- [x] Link for GitHub present
- [x] Link for LinkedIn present
- [x] Link or display of technologies powering the site is present
