### ISSUE TITLE
[STORY] Easy navigation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#30]
**Related epic**
#5 

**Story**

As a customer,
I can browse the site intuitively,
So that I have a positive emotional experience

**Tasks**
- [x] Implement navbar with well defined links
- [x] Test for responsiveness
- [x] Test link integrity

**Acceptance criteria**
- [x] All sections of the site are accessible from the navbar
- [x] All links return to the labelled page
- [x] Navbar is responsive to screen sizes and orientations
