### ISSUE TITLE
[STORY] Accessible browsing

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#31]
**Related epic**
#5

**Story**

As a customer with accessibility concerns,
I can have my accessibility needs met as I browse the site,
So that my experience of the site in not compromised

**Tasks**
- [x] Implement sufficient contrast ratios across pages
- [x] Full implementation of ARIA attributes
- [x] Perform Lighthouse checks across pages to verify accessibility ratings
- [x] Perform WAVE check to expose and correct any warnings
- [x] Implement page titles across pages

**Acceptance criteria**
- [x] 90/100 minimum threshold for Lighthouse accessibility checks across pages
- [x] No WAVE errors exposed across pages
- [x] All pages across the site have a head title
