### ISSUE TITLE
[STORY] Breadcrumbs

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#32]
**Related epic**
#5

**Story**

As a customer,
I can easily view a breadcrumb browsing trail on each page,
So that I always know where I am and can return to any other page

**Tasks**
- [ ] Research and implement Bootstrap breadcrumb implementation

**Acceptance criteria**
- [ ] Breadcrumbs are present across pages throughout the site
- [ ] All links direct to the expected page
