### ISSUE TITLE
[STORY] Feedback on actions

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#33]
**Related epic**
#5

**Story**

As a customer or admin,
I can view feedback on my actions when interacting with the site,
So that my actions are confirmed and I can correct any input errors as necessary

**Tasks**
- [x] Implement Django messaging system in views to confirm all user interaction scenarios
- [x] Ensure alert level styling is in effect
- [x] Enable auto-dismissal of messages
- [x] Include messages in appropriate views
- [x] Use JavaScript to handle any asynchronous messages

**Acceptance criteria**
- [x] Correct type of message class is applied by message level
- [x] Authentication messages auto dismisses after four seconds
- [x] Item added to basket message auto dismisses after eight seconds
- [x] Login message present
- [x] Logout message present
- [x] New address saved message present
- [x] Default address saved message present
- [x] Address updated message present
- [x] Address deleted message present
