### ISSUE TITLE
[STORY] Action confirmation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#36]
**Related epic**
#5

**Story**

As a customer or admin,
I can receive a confirmation message for appropriate actions,
So that I can return from a mistaken input without altering my data

**Tasks**
- [x] Implement confirmation on account events such as logging out
- [x] Confirm all payments before customer will be charged
- [x] Provide option to confirm all actions that delete entries from the database

**Acceptance criteria**
- [x] User must confirm to log out
- [x] User must confirm to proceed with payment
- [x] User must confirm any action that will delete a database entry
- [x] Grand total is shown before user submits payment
