### ISSUE TITLE
[STORY] Keyword implementation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#37]
**Related epic**
#6

**Story**

As an admin,
I can strategically implement keywords throughout the content of the site,
So that I can maximize my SEO efforts

**Tasks**
- [x] Research effective short and long tail keywords
- [x] Make use of semantic HTML elements to bring attention to these keywords

**Acceptance criteria**
- [x] Keywords are present in heading and other emphasized HTML tags
- [x] 90/100 minimum threshold for Lighthouse SEO checks across pages
