### ISSUE TITLE
[STORY] Sitemap

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#39]
**Related epic**
#6

**Story**

As an admin,
I can implement a sitemap,
So that So that search engine crawlers can index the site effectively for SEO purposes

**Tasks**
- [x] Generate and deploy a sitemap
- [x] Ensure use of canonical URLs

**Acceptance criteria**
- [x] Sitemap is present in deployment
- [x] All URLs are canonical
