### ISSUE TITLE
[STORY] Facebook business page

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#40]
**Related epic**
#7 

**Story**

As an admin,
I can create and link to a Facebook business page,
So that I can expand my visibility and reach

**Tasks**
- [x] Create Facebook business page
- [x] Include reciprocal links between the Facebook page and main site

**Acceptance criteria**
- [x] Facebook business page is created with information relevant to the main site
- [x] Links are present on the main site to link to the Facebook page
- [x] Links are present on the Facebook page to link to the main site
