### ISSUE TITLE
[STORY] Newsletter

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#41]
**Related epic**
#7

**Story**

As an admin,
I can implement a newsletter that users can sign up for,
So that I can target marketing to interested customers

**Tasks**
- [x] Create form for users to sign up for the newsletter
- [x] Create newsletter content
- [x] Implement mechanism to send the newsletter to the appropriate email address

**Acceptance criteria**
- [x] Newsletter sign up form is present
- [x] Newsletter content is displayed as intended
- [x] Newsletter is sent to the correct email address
