### ISSUE TITLE
[STORY] Introductory discount

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#42]
**Related epic**
#7

**Story**

As an admin,
I can provide a discount for customers that first sign up for the newsletter,
So that I can increase purchase incentive 

**Tasks**
- [ ] Ensure models can accommodate discount factors
- [ ] Implement discount code with appropriate verification

**Acceptance criteria**
- [ ] Discount code can be applied at checkout
- [ ] Discount code can only be used once per customer
- [ ] Discount code cannot be stacked
