### ISSUE TITLE
[STORY] Automated testing

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#43]
**Related epic**
#8

**Story**

As an admin,
I can write automated tests,
So that I can verify that my data can be manipulated as intended and site functionality is correct

**Tasks**
- [x] Write appropriate automated tests for forms
- [x] Write appropriate automated tests for models
- [x] Write appropriate automated tests for the functionality of each view
- [x] Ensure these are present in each app for which they are required

**Acceptance criteria**
- [x] Forms automated tests pass
- [x] Models automated tests pass
- [x] Views automated tests pass
