### ISSUE TITLE
[STORY] Test coverage

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#44]
**Related epic**
#8

**Story**

As an admin,
I can generate a coverage report on my automated tests,
So that I can see which tests have been covered, or still need to be performed

**Tasks**
- [x] Run coverage report to expose tests that must be written
- [x] Run coverage report once automated tests have been written and passing to plan manual testing procedure

**Acceptance criteria**
- [x] Coverage report is generated
- [x] Elements not covered in the report are used to form the basis of the manual testing procedure
