### ISSUE TITLE
[STORY] Manual testing

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#45]
**Related epic**
#8

**Story**

As an admin,
I can perform manual tests,
So that I can ensure correct functionality that could not be verified with automated testing

**Tasks**
- [x] Refer to coverage report to create list of elements that must be tested manually
- [x] Perform and record the results of manual tests
- [x] Test Python code
- [x] Test JavaScript functionality

**Acceptance criteria**
- [x] Report is generated which covers all elements not tested in the coverage report
- [x] All elements are manually tested
- [x] All elements' passing status are accurately in the manual testing report
- [x] Python manual testing covered
- [x] JavaScript manual testing covered
- [x] URL role-based access covered
