### ISSUE TITLE
[STORY] Integrated site deployment

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#46]
**Related epic**
#9

**Story**

As an admin,
I can deploy the site with all core features integrated,
So that I perform my business functions in full

**Tasks**
- [x] Successfully deploy site to hosting platform
- [x] Test administration and authorization features in production
- [x] Confirm payments are accepted and rejected as appropriate
- [x] Ensure webhooks are handled correctly in production
- [x] Ensure static and media files are correctly handled in production

**Acceptance criteria**
- [x] Site is deployed on hosting platform without errors
- [x] Administrative CRUD functions work successfully
- [x] Authorization for account actions work as intended
- [x] Appropriate response is received for payment actions
- [x] Appropriate response is received by the webhook
- [x] Static and media files are correctly represented on the deployed site
- [x] Emails are sent to users to confirm account and any orders
