### ISSUE TITLE
[STORY] Basic models

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#47]
**Related epic**
#1 

**Story**

As an admin,
I can create basic database models,
So that I can build out basic site functionality whilst reducing the opportunity for errors

**Tasks**
- [x] Create products app
- [x] Create a basic product model
- [x] Create a related category model
- [x] Register products app
- [x] Run migrations
- [x] Create superuser
- [x] Register products models to Django admin

**Acceptance criteria**
- [x] Product app created
- [x] Product model has a name
- [x] Product model has a price
- [x] Product model has a related category
- [x] Products app is registered in Django settings
- [x] Migrations completed
- [x] Superuser created
- [x] Product and Category models registered in Django admin
