### ISSUE TITLE
[STORY] Basic Project start

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#48]
**Related epic**
#1 

**Story**

As an admin,
I can start a basic Django project,
So that I can build out my site functionality based on different user stories

**Tasks**
- [ ] Make relevant package imports
- [ ] Start Django project
- [ ] Create basic products app and models
- [ ] Create file for environment variables

**Acceptance criteria**
- [ ] Django package imported
- [ ] Django project started
- [ ] Products app created
- [ ] File created for environment variables
- [ ] Secret keys removed from Django settings before commit
