### ISSUE TITLE
[STORY] Dummy products

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#49]
**Related epic**
#1 

**Story**

As an admin,
I can create some dummy products in the database,
So that I can build and test the products app functionality with minimal errors

**Tasks**
- [x] Create several categories in admin panel
- [x] Create sever products in admin panel
- [x] Ensure different categories, product names and prices are used

**Acceptance criteria**
- [x] Two categories created
- [x] Three products created, with differing names and prices
