### ISSUE TITLE
[STORY] Initial test coverage

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#50]
**Related epic**
#8

**Story**

As an admin,
I can generate a testing coverage report at the start of the project,
So that I can see which tests need to be covered as the project grows

**Tasks**
- [x] Install coverage package
- [x] Run HTML test report
- [x] Write any automated tests as required
- [x] Update tests to accommodate any model or URL changes

**Acceptance criteria**
- [x] Coverage package installed
- [x] HTML test report generated
- [x] Tests created for untested elements in custom files
- [x] Model tests pass
- [x] View tests pass
