### ISSUE TITLE
[STORY] Basic product page

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#51]
**Related epic**
#1 

**Story**

As an admin,
I can create a basic page to list the products in the database,
So that I can later expand on the way products are displayed on the site

**Tasks**
- [x] Set up URLs
- [x] Set up view to display all products

**Acceptance criteria**
- [x] All current products are displayed at the root URL
