### ISSUE TITLE
[STORY] Basic templates and styling

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#52]
**Related epic**
#5  

**Story**

As an admin,
I can create and style basic HTML templates,
So that I can develop the pages of the site quickly from my wireframe designs

**Tasks**
- [x] Create base template
- [x] Set up relevant directories
- [x] Enable required directory paths in Django
- [x] Add blocks for different types of content
- [x] Include Bootstrap

**Acceptance criteria**
- [x] Base template present
- [x] Template inheritance in effect
- [x] Bootstrap styling in effect
- [x] Static files load correctly
