### ISSUE TITLE
[STORY] Initial navigation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#53]
**Related epic**
#5

**Story**

As an admin,
I can include a template navbar component,
So that I can expand navigation and search functionality as the site grows

**Tasks**
- [x] Include a Bootstrap navbar component
- [x] Update links as URLs are configured
- [x] Add basic styling with brand theme

**Acceptance criteria**
- [x] Responsive nabvar is present
- [x] Link to home page working
- [x] Brand font and colouring implemented
