### ISSUE TITLE
[STORY] Initial SEO HTML implementation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#54]
**Related epic**
#6 

**Story**

As an admin,
I can include initial meta tags related to the business,
So that I can start my SEO efforts for the site

**Tasks**
- [ ] Include appropriate meta tags that pertain to the business

**Acceptance criteria**
- [ ] Meta description present
- [ ] Meta keywords present
