### ISSUE TITLE
[STORY] Home page

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#58]
**Related epic**
#1 

**Story**

As a customer,
I can access the site's homepage,
So that I can see which parts of the site I can access and which products are new

**Tasks**
- [x] Create app for home
- [x] Update URLs as required
- [x] Return recent products in the home page context
- [x] Configure tests for home app and any updated URLs

**Acceptance criteria**
- [x] Home app created
- [x] Home page accessible at domain name root
- [x] _n_ number of recent products are shown on the homepage
- [x] Home app test pass
