### ISSUE TITLE
[STORY] Require login for transactions

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#64]
**Related epic**
#3

**Story**

As an admin,
I can require users to sign in for transactional actions,
So that I can ensure proper, secure transaction and API functionality

**Tasks**
- [x] Decorate appropriate views to require login
- [x] Inform customers that login is required for certain actions via messages
- [x] Change button content depending on login status

**Acceptance criteria**
- [x] Basket actions require login
- [x] Checkout actions require login
- [x] Basket button gives login prompt when logged out
- [x] Add to basket button gives login prompt when logged out
- [x] Checkout page is inaccessible when logged out
