### ISSUE TITLE
[STORY] Custom error pages

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#69]
**Related epic**
#5 

**Story**

As a customer,
I can view a customized error page if I enter the wrong URL,
So that I can continue browsing quickly

**Tasks**
- [x] Extend base template with custom 404 page
- [x] Provide relevant background image
- [x] Link back to home page

**Acceptance criteria**
- [x] Custom 404 page is loaded when the URL is not found on the domain
- [x] Link to homepage is clearly shown
