### ISSUE TITLE
[STORY] Incentivize spending for free shipping

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#70]
**Related epic**
#2

**Story**

As an admin,
I can notify customers of the free delivery threshold upfront,
So that I can incentivize more purchases

**Tasks**
- [x] Add homepage banner detailing delivery stipulations
- [x] Calculate difference at basket summary page to show customers how much more to spend to qualify for free delivery
- [x] Add context processor to make variables available across pages

**Acceptance criteria**
- [x] Banner is present below navbar to highlight shipping stipulations
- [x] Variables in banner reflect shipping variables set in the order model
- [x] Basket summary notifies user how much more to spend for free delivery
- [x] Values update dynamically
- [x] Alert classes change dynamically
