### ISSUE TITLE
[STORY] Confirmation email

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#71]
**Related epic**
#2 

**Story**

As a customer,
I can receive a confirmation email after payment,
So that I have a record of my transaction

**Tasks**
- [x] Create email include templates
- [x] Create webhook method to send email
- [x] Check that correct content is displayed in the email title and body

**Acceptance criteria**
- [x] Includes present for email title and body
- [x] Template variables render correctly in the email text
- [x] Message is sent to the correct recipient
