### ISSUE TITLE
[STORY] Mark products as sold

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#73]
**Related epic**
#1 

**Story**

As an admin, 
I can I can automatically mark products as sold one payment has gone through,
So that customers don't try to buy out of stock products

**Tasks**
- [x] Add boolean to product model to mark if sold
- [x] Update admin display
- [x] Update value to true in webhook
- [x] Provide visual notification and styling for sold products
- [x] Ensure sold products cannot be added to the basket

**Acceptance criteria**
- [x] Product model has boolean field for sold status, which defaults to false
- [x] Sold item status is reflected in front end list template
- [x] Sold item status is reflected in front end detail template
- [x] Sold item cannot be added to the basket
- [x] On successful payment, each item sold has its sold status set to true
