### ISSUE TITLE
[STORY] Privacy policy

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#74]
**Related epic**
#4 

**Story**

As a customer,
I can view the site's privacy policy,
So that I can be informed about my GDPR rights

**Tasks**
- [x] Generate privacy policy
- [x] Embed link in footer

**Acceptance criteria**
- [x] GDPR-compliant privacy policy has been generated
- [x] Privacy policy is linked in footer
