### ISSUE TITLE
[STORY] Complete documentation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#76]
**Related epic**
#10 

**Story**

As a developer,
I can fully document the process of bringing the site to life,
So that I can collaborate with developers and product owners in the future

**Tasks**
- [x] Create the sections listed in the acceptance criteria
- [x] Complete content for listed sections
- [x] Show supporting imagery such as screenshots or graphs
- [x] Perform spelling, grammar and readability check

**Acceptance criteria**
- [x] Deployment links
- [x] Introduction
- [x] Context
- [x] Five stages of UX design, including wireframes
- [x] Features, including screenshots
- [x] Web marketing
- [x] SEO
- [x] Data modelling, with schema diagrams
- [x] Testing
- [x] Validation
- [x] Bugs
- [x] Deployment, including cloning and forking
- [x] Acknowledgements
