### ISSUE TITLE
[STORY] Total navigation

### ISSUE THREAD

**Issue by jts272** [jts272/pp5-retro-replay#77]
**Related epic**
#5 

**Story**

As a customer,
I can access every page on the site from a link, including sold products,
So that I am able to navigate to every part of the site easily

**Tasks**
- [x] Set up url to display solid products
- [x] Set up sold products manager
- [x] Create view with solid products context
- [x] Link to sold products list in navbar
- [x] Write automated tests for new view
- [x] Update sitemap

**Acceptance criteria**
- [x] Sold products can be accessed at their absolute url
- [x] Sold products link present on navabar dropdown
- [x] Only sold products are returned in the queryset
- [x] Updated sitemap is present
